### ISSUE TITLE
Startup after flashing error

### ISSUE THREAD

**Issue by DSolo03** [dreemurrs-embedded/edk2-lavender#2]
I build the uefi.img and flashing it. After reboot I get that error:
![image](https://user-images.githubusercontent.com/61384845/90978954-23489c80-e55a-11ea-89c0-577e323a6da0.png)
I try to create esp partition on SD-card, but it's not working. How to fix this?

**Comment by Danct12** [comment]
Please do not mix other XBL binaries together. Closing.
